#!/usr/bin/expect
set timeout 200
set login   0
set ip      [lindex $argv 0]
set mac     [lindex $argv 1]
spawn ssh root@$ip -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR
 expect {
 "$mac"
   {
    exit 2
   }
 "hciconfig hci0 reset"
   {
    sleep 3; send "hcitool lescan\n"; exp_continue
   }
 "#"
   {
    if {$login==0} {set login 1;send "hciconfig hci0 reset\n"; exp_continue} else {exp_continue}
   }
 eof
   {}
 }

