#!/usr/bin/expect
set timeout 60
set login 0
set ip4      [lindex $argv 0]
set ip6      [lindex $argv 1]

spawn ssh root@$ip4 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR
 expect {
 "yes/no"
   {
    sleep 1; send "yes\n"; exp_continue
   }
 "home"
   {
    sleep 1; send "exit\n"; exit 2
   }
 "#"
   {
    sleep 1;
    if {$login==0} {set login 1; send "ssh root@$ip6%bt0 -i /tmp/ostro_qa_rsa ls /\n"; exp_continue} else {exp_continue}
   }
 eof
   {}
 }

