#!/bin/sh
main()
{
    /usr/bin/naui
    while true; do
         sleep 10
         /usr/bin/naui update
    done & exit 0
}

die()
{
    [ -c "$tty" ] && echo "exiting: $@" > $tty
    exit 1
}

main "$@"
