SUMMARY = "The JavaScript Robotics and Hardware Programming Framework"
HOMEPAGE = "https://johnny-five.io"
SRC_URI = "npm://registry.npmjs.org;name=johnny-five;version=${PV} \
           file://npm-shrinkwrap.json;subdir=npmpkg \
           file://lockdown.json;subdir=npmpkg"

S = "${WORKDIR}/npmpkg"

NPM_LOCKDOWN := "${THISDIR}/${PN}/lockdown.json"
NPM_SHRINKWRAP := "${THISDIR}/${PN}/npm-shrinkwrap.json"
DEPENDS += "bash"
RDEPENDS_johnny-five-serialport-node-pre-gyp-request-node-uuid += "bash"

inherit npm

LICENSE = "BSD-3-Clause & BSD & ISC & Apache-2.0 & BSD-2-Clause & MIT"
LIC_FILES_CHKSUM = "file://node_modules/serialport/LICENSE;md5=ff2442a554fd28ad7d07322f297c2f7d \
                    file://node_modules/serialport/node_modules/nan/LICENSE.md;md5=365dd94f3b619ca5566e5fb51f32c0e6 \
                    file://node_modules/serialport/node_modules/debug/node_modules/ms/LICENSE;md5=2be2157b55ea281b7f4969d7ba05eea2 \
                    file://node_modules/serialport/node_modules/object.assign/LICENSE;md5=2b439ca9e99134dee172a7cc6d989174 \
                    file://node_modules/serialport/node_modules/object.assign/node_modules/define-properties/LICENSE;md5=53ffc646fdb83e45279cfe7105e5157b \
                    file://node_modules/serialport/node_modules/object.assign/node_modules/define-properties/node_modules/foreach/LICENSE;md5=b2225091caf5effa363ef7016fa2b0ba \
                    file://node_modules/serialport/node_modules/object.assign/node_modules/function-bind/LICENSE;md5=e7417c1a8ad83f88bcac21ad440d48b2 \
                    file://node_modules/serialport/node_modules/object.assign/node_modules/object-keys/LICENSE;md5=0026e638d7d5c5f2768864ce0074f8ad \
                    file://node_modules/serialport/node_modules/node-pre-gyp/LICENSE;md5=7e13c3cf883a44ebcc74a8f568c0f6fb \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/LICENSE.MIT;md5=e0f70a42adf526e6f5e605a94d98a420 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/LICENSE.BSD;md5=e7a2a325a0069e82aff675bbf74464a0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/LICENSE.APACHE2;md5=ffcf739dca268cb0f20336d6c1a038f1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/node_modules/minimist/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/node_modules/deep-extend/LICENSE;md5=74959162613f2777f3ef55bdb8b74c89 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/node_modules/ini/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rc/node_modules/strip-json-comments/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/semver/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/mkdirp/LICENSE;md5=b2d989bc186e7f6b418a5fdd5cc0b56b \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/mkdirp/node_modules/minimist/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/ansi/LICENSE;md5=694e396551033371686c80d3a1a69e88 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/LICENSE;md5=039a23da29f56411e6d75d7b7bc9de13 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates/License;md5=039225978c07bc42e8c0ef2f72b81c09 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/LICENSE;md5=d7351a4fc8e956f1a68413490d5e655e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/process-nextick-args/license.md;md5=216769dac98a78ec088ee7cc6fad1dfa \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/string_decoder/LICENSE;md5=fcf5cfdc777e49f11402422c72a86f43 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/core-util-is/LICENSE;md5=6126e36127d20ec0e2f637204a5c68ff \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/util-deprecate/LICENSE;md5=b7c99ef4b0f3ad9911a52219947f8cf0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/LICENSE;md5=43abbc6f9093aea69560715033788727 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padstart/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padstart/node_modules/lodash._basetostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padstart/node_modules/lodash._baseslice/LICENSE;md5=3229b60739f3d575a1e683f9d74102ea \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padstart/node_modules/lodash.tostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash._basetostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash._baseslice/LICENSE;md5=3229b60739f3d575a1e683f9d74102ea \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash.tostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padend/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padend/node_modules/lodash._basetostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padend/node_modules/lodash._baseslice/LICENSE;md5=3229b60739f3d575a1e683f9d74102ea \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padend/node_modules/lodash.tostring/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/has-unicode/LICENSE;md5=2bab5b1c26e9c44fc4e489bb98cfb196 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/nopt/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/nopt/node_modules/abbrev/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/LICENSE;md5=34c65f5b9b91f31827910d3b54bd6497 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/block-stream/LICENCE;md5=c695aba12d799c74e770d90e1c5d59aa \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/block-stream/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/LICENSE;md5=fd63805fd8e3797063b247781e5ee6e4 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/LICENSE;md5=bbd174e5c1525a215e2f38ebfcca16e9 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/uid-number/LICENSE;md5=90a3ca01a5efed8b813a81c6c8fa2e63 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs/LICENSE;md5=fd63805fd8e3797063b247781e5ee6e4 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/once/node_modules/wrappy/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/LICENSE;md5=d7351a4fc8e956f1a68413490d5e655e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/process-nextick-args/license.md;md5=216769dac98a78ec088ee7cc6fad1dfa \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/string_decoder/LICENSE;md5=fcf5cfdc777e49f11402422c72a86f43 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/core-util-is/LICENSE;md5=6126e36127d20ec0e2f637204a5c68ff \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/util-deprecate/LICENSE;md5=b7c99ef4b0f3ad9911a52219947f8cf0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/LICENSE.md;md5=7fa99ddc3424107350ca6e9a24552085 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/LICENSE;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/LICENSE.md;md5=7fa99ddc3424107350ca6e9a24552085 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/once/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/once/node_modules/wrappy/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/path-is-absolute/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight/LICENSE;md5=90a3ca01a5efed8b813a81c6c8fa2e63 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight/node_modules/wrappy/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/stringstream/LICENSE.txt;md5=3b3d0996fc07ae2d89c4659b9ffcbe2e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/qs/LICENSE;md5=d5c7c6dc45a33a0a9620ed81315672d7 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/aws-sign2/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/is-typedarray/LICENSE.md;md5=aea1cde69645f4b99be4ff7ca9abcce1 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/mime-types/LICENSE;md5=bf1f9ad1e2e1d507aef4883fff7103de \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/mime-types/node_modules/mime-db/LICENSE;md5=c8d3a30332ecb31cfaf4c0a06da18f5c \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/tunnel-agent/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/tough-cookie/LICENSE;md5=ceb9c658d7a5d62bee6628c46832168e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/node-uuid/LICENSE.md;md5=465a37064da7d113df228e930a1cfdcd \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/extend/LICENSE;md5=33d9f7a91df276ec16aa941032ee1476 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data/License;md5=7aa505292e2636a9e59d4d3f258f4819 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data/node_modules/async/LICENSE;md5=dc113e0fc4029c29942399ad22425402 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/LICENSE;md5=38ecf0a3a3894f404ca99c2a08924afc \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/jsprim/LICENSE;md5=bc3c23d98d7aa86bbf232058884e19b2 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/LICENSE;md5=bc3c23d98d7aa86bbf232058884e19b2 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/extsprintf/LICENSE;md5=bc3c23d98d7aa86bbf232058884e19b2 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/LICENSE;md5=38ecf0a3a3894f404ca99c2a08924afc \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/jodid25519/LICENSE;md5=5e6d2cd78a8664b38651e01b76a2323a \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/asn1/LICENSE;md5=5ce2f42143c298495637e28e40cd5462 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/jsbn/LICENSE;md5=c6ea389b6b52325149beeec27075c5ac \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/ecc-jsbn/LICENSE;md5=0d289b6d63cbcc18e4b2af9a5bd28b54 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/ecc-jsbn/lib/LICENSE-jsbn;md5=32052d48bacabd1c02e56c6889082a27 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/getpass/LICENSE;md5=38ecf0a3a3894f404ca99c2a08924afc \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/LICENSE;md5=bfa81591facc9224e4c7451c8dc12958 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/escape-string-regexp/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/ansi-styles/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend/LICENCE;md5=96bcdf84e670aafacac9e094bce29ac9 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/LICENSE;md5=9befe7026bf915886cd566a98117c80e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/LICENSE;md5=34aed54d1454553d81a843e946b173a0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/license;md5=be72c3ad86c1c4e9578a1945b082b17d \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/license;md5=be72c3ad86c1c4e9578a1945b082b17d \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/aws4/LICENSE;md5=ff6f181928a91d8631d565516b4db3cb \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/combined-stream/License;md5=5270b4ddb6700d0a820e6d066744589c \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/License;md5=5270b4ddb6700d0a820e6d066744589c \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/oauth-sign/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/isstream/LICENSE.md;md5=1798150b9d70250c42b55b3530e6af2b \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/caseless/LICENSE;md5=e9dadf023ba6ebd98e3e0acb6e2470e3 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/forever-agent/LICENSE;md5=f3f8ead5440d1c311b45be065d135d90 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/LICENSE.md;md5=7489efd5cf7c4575f9898b7eab7aeeb0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/LICENSE;md5=d7351a4fc8e956f1a68413490d5e655e \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/process-nextick-args/license.md;md5=216769dac98a78ec088ee7cc6fad1dfa \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/string_decoder/LICENSE;md5=fcf5cfdc777e49f11402422c72a86f43 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is/LICENSE;md5=6126e36127d20ec0e2f637204a5c68ff \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/util-deprecate/LICENSE;md5=b7c99ef4b0f3ad9911a52219947f8cf0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/inherits/LICENSE;md5=5b2ef2247af6d355ae9d9f988092d470 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/json-stringify-safe/LICENSE;md5=82703a69f6d7411dde679954c2fd9dca \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/LICENSE;md5=e027b6d4642f6a1131d030b119fa8f50 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/sntp/LICENSE;md5=6b3f1791e9fe721a645d793af56193c6 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/boom/LICENSE;md5=d5c0c437eeeff35277efeadaec74e821 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/cryptiles/LICENSE;md5=6e2f87804ca8061967f7891dfb34f6f0 \
                    file://node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/hoek/LICENSE;md5=0ae863d44c9a840e5cc04241d8d9c736 \
                    file://node_modules/serialport/node_modules/commander/LICENSE;md5=25851d4d10d6611a12d5571dab945a00 \
                    file://node_modules/serialport/node_modules/commander/node_modules/graceful-readlink/LICENSE;md5=b0270ddb7ee6643eee76e80113234806 \
                    file://node_modules/serialport/node_modules/es6-promise/LICENSE;md5=6e73e44544d76c1978a076a8292d031a \
                    file://node_modules/firmata/node_modules/es6-shim/LICENSE;md5=d0c77f283294830f63477f1e18bb7368 \
                    file://node_modules/chalk/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/strip-ansi/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/strip-ansi/node_modules/ansi-regex/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/escape-string-regexp/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/supports-color/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/ansi-styles/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/has-ansi/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex/license;md5=a12ebca0510a773644101a99a867d210 \
                    file://node_modules/temporal/LICENSE-MIT;md5=492159b26278d7f489872e07e408a43d \
                    file://node_modules/browser-serialport/LICENSE.md;md5=b1d7bd8a2d6a81879349c2034afa7e8e \
                    file://node_modules/color-convert/LICENSE;md5=330031db3ec2b47f6e9d7923b8e1f95b \
                    file://node_modules/lodash.clonedeep/LICENSE;md5=fe563f0ce45a88395a73e7dc46f5339e \
                    file://node_modules/lodash.clonedeep/node_modules/lodash._baseclone/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/lodash.debounce/LICENSE;md5=a3b2b7770df62392c164de4001b59f8f \
                    file://node_modules/es6-shim/LICENSE;md5=508a108665f3b7140d113af9c579ba24"

LICENSE_${PN}-browser-serialport = "MIT"
LICENSE_${PN}-chalk-ansi-styles = "MIT"
LICENSE_${PN}-chalk-escape-string-regexp = "MIT"
LICENSE_${PN}-chalk-has-ansi-ansi-regex = "MIT"
LICENSE_${PN}-chalk-has-ansi = "MIT"
LICENSE_${PN}-chalk-strip-ansi-ansi-regex = "MIT"
LICENSE_${PN}-chalk-strip-ansi = "MIT"
LICENSE_${PN}-chalk-supports-color = "MIT"
LICENSE_${PN}-chalk = "MIT"
LICENSE_${PN}-color-convert = "MIT"
LICENSE_${PN}-ease-component = "MIT"
LICENSE_${PN}-es6-shim = "MIT"
LICENSE_${PN}-firmata-browser-serialport = "MIT"
LICENSE_${PN}-firmata-es6-shim = "MIT"
LICENSE_${PN}-firmata = "MIT"
LICENSE_${PN}-lodash.clonedeep-lodash.-baseclone = "MIT"
LICENSE_${PN}-lodash.clonedeep = "MIT"
LICENSE_${PN}-lodash.debounce = "MIT"
LICENSE_${PN}-nanotimer = "ISC"
LICENSE_${PN}-serialport-bindings = "MIT"
LICENSE_${PN}-serialport-commander-graceful-readlink = "MIT"
LICENSE_${PN}-serialport-commander = "MIT"
LICENSE_${PN}-serialport-debug-ms = "MIT"
LICENSE_${PN}-serialport-debug = "MIT"
LICENSE_${PN}-serialport-es6-promise = "MIT"
LICENSE_${PN}-serialport-nan = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-mkdirp-minimist = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-mkdirp = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-nopt-abbrev = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-nopt = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-ansi = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-delegates = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-core-util-is = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-isarray = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-process-nextick-args = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-string-decoder = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream-util-deprecate = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet-readable-stream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-are-we-there-yet = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-has-unicode = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.pad-lodash.-baseslice = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.pad-lodash.-basetostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.pad-lodash.tostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padend-lodash.-baseslice = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padend-lodash.-basetostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padend-lodash.tostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padend = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padstart-lodash.-baseslice = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padstart-lodash.-basetostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padstart-lodash.tostring = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.padstart = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-lodash.pad = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-strip-ansi-ansi-regex = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge-strip-ansi = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog-gauge = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-npmlog = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rc-deep-extend = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rc-ini = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rc-minimist = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rc-strip-json-comments = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rc = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-aws-sign2 = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-request-aws4 = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-core-util-is = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-isarray = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-process-nextick-args = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-string-decoder = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream-util-deprecate = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl-readable-stream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-bl = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-caseless = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-request-combined-stream-delayed-stream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-combined-stream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-extend = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-forever-agent = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-request-form-data-async = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-form-data = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-ansi-styles = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-escape-string-regexp = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-has-ansi-ansi-regex = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-has-ansi = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-strip-ansi-ansi-regex = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-strip-ansi = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk-supports-color = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-chalk = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid-generate-function = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid-generate-object-property-is-property = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid-generate-object-property = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid-jsonpointer = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid-xtend = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-is-my-json-valid = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-pinkie-promise-pinkie = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator-pinkie-promise = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-har-validator = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-request-hawk-boom = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-hawk-cryptiles = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-hawk-hoek = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-hawk-sntp = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-hawk = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-assert-plus = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-jsprim-extsprintf = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-jsprim-json-schema = "BSD"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-jsprim-verror = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-jsprim = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-asn1 = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-assert-plus = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-dashdash-assert-plus = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-dashdash = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-ecc-jsbn = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-getpass-assert-plus = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-getpass = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-jodid25519 = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk-jsbn = "BSD"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature-sshpk = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-http-signature = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-is-typedarray = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-isstream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-json-stringify-safe = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-request-mime-types-mime-db = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-mime-types = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-node-uuid = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-oauth-sign = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-request-qs = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-stringstream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-request-tough-cookie = "BSD-3-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-request-tunnel-agent = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-request = "Apache-2.0"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-inflight-wrappy = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-inflight = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-minimatch-brace-expansion-balanced-match = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-minimatch-brace-expansion-concat-map = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-minimatch-brace-expansion = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-minimatch = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-once-wrappy = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-once = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob-path-is-absolute = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf-glob = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-rimraf = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-semver = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-block-stream = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-fstream-graceful-fs = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-fstream = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-debug = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-graceful-fs = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore-minimatch-brace-expansion-balanced-match = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore-minimatch-brace-expansion-concat-map = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore-minimatch-brace-expansion = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore-minimatch = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-ignore = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-fstream = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-once-wrappy = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-once = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-core-util-is = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-inherits = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-isarray = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-process-nextick-args = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-string-decoder = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream-util-deprecate = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-readable-stream = "MIT"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack-uid-number = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp-tar-pack = "BSD-2-Clause"
LICENSE_${PN}-serialport-node-pre-gyp-tar = "ISC"
LICENSE_${PN}-serialport-node-pre-gyp = "BSD-3-Clause"
LICENSE_${PN}-serialport-object.assign-define-properties-foreach = "MIT"
LICENSE_${PN}-serialport-object.assign-define-properties = "MIT"
LICENSE_${PN}-serialport-object.assign-function-bind = "MIT"
LICENSE_${PN}-serialport-object.assign-object-keys = "MIT"
LICENSE_${PN}-serialport-object.assign = "MIT"
LICENSE_${PN}-serialport = "MIT"
LICENSE_${PN}-temporal = "MIT"
LICENSE_${PN} = "MIT"
