#!/bin/bash
#############################################################################
#          Copyright (c) 2012, 2013, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Intel Corporation nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################


#  Set the netlabel values in the smackfs netlabel
#  Set the Smack rules for System for Network::Cloud
#  Set the Smack rules for System for Network::Local

while true; do
 if [ -f /sys/fs/smackfs/load2 ] 
 then
  LOCALNET=`netvalue | grep -v lo | awk '{print $8$10}'`
  echo $LOCALNET Network::Local > /sys/fs/smackfs/netlabel
  echo 0.0.0.0/0 Network::Cloud > /sys/fs/smackfs/netlabel
  echo 127.0.0.0/8 -CIPSO > /sys/fs/smackfs/netlabel
  echo System Network::Cloud w > /sys/fs/smackfs/load2
  echo System Network::Local w > /sys/fs/smackfs/load2
  echo Network::Cloud System w > /sys/fs/smackfs/load2
  echo Network::Local System w > /sys/fs/smackfs/load2
  
  echo User Network::Cloud w > /sys/fs/smackfs/load2
  echo User Network::Local w > /sys/fs/smackfs/load2
  echo Network::Cloud User w > /sys/fs/smackfs/load2
  echo Network::Local User w > /sys/fs/smackfs/load2
 fi
 sleep 300
done
