#!/bin/sh

LOGFILE=/var/log/tlm-launch.log

echo "home: $HOME" > $LOGFILE

LAUNCHER_INI_FILE="$HOME/tlm-app-session.ini"
cat /dev/null >| $LAUNCHER_INI_FILE
for f in $HOME/apps_rw/*/tlm-launch ; do
    if [ -f $f -a -x $f ] ; then
        echo "M:$f" >> $LAUNCHER_INI_FILE
    fi
done

exec tlm-launcher -b -f $LAUNCHER_INI_FILE "$@"
